spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  thymeleaf:
    cache: true

logging:
  level:
    com.news: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  file:
    name: /app/logs/news-application.log
    max-size: 10MB
    max-history: 30

server:
  error:
    include-message: never
    include-binding-errors: never
