spring:
  application:
    name: news-application
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    
server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.news: INFO
    org.springframework.security: WARN
